/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "alcazaba": {
    "base": "alcazaba",
    "width": 3000,
    "height": 2000,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "alhambra": {
    "base": "alhambra",
    "width": 1440,
    "height": 2299,
    "fallbackWidth": 1440,
    "fallbackHeight": 2299,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "caminito": {
    "base": "caminito",
    "width": 1400,
    "height": 2100,
    "fallbackWidth": 1400,
    "fallbackHeight": 2100,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coast": {
    "base": "coast",
    "width": 3552,
    "height": 2664,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 3840,
    "height": 1950,
    "fallbackWidth": 1920,
    "fallbackHeight": 975,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 3840,
    "height": 2880,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 680,
    "height": 1024,
    "fallbackWidth": 680,
    "fallbackHeight": 1024,
    "widths": [
      320,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 3840,
    "height": 2560,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "granada": {
    "base": "granada",
    "width": 3508,
    "height": 2387,
    "fallbackWidth": 800,
    "fallbackHeight": 544,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 1400,
    "height": 2100,
    "fallbackWidth": 1400,
    "fallbackHeight": 2100,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "historic": {
    "base": "historic",
    "width": 680,
    "height": 1024,
    "fallbackWidth": 680,
    "fallbackHeight": 1024,
    "widths": [
      320,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "mijas": {
    "base": "mijas",
    "width": 1280,
    "height": 853,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 1440,
    "height": 2299,
    "fallbackWidth": 1440,
    "fallbackHeight": 2299,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "photography": {
    "base": "photography",
    "width": 1400,
    "height": 2100,
    "fallbackWidth": 1400,
    "fallbackHeight": 2100,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "private": {
    "base": "private",
    "width": 3840,
    "height": 1950,
    "fallbackWidth": 800,
    "fallbackHeight": 406,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "ronda": {
    "base": "ronda",
    "width": 3840,
    "height": 1950,
    "fallbackWidth": 1920,
    "fallbackHeight": 975,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "walking": {
    "base": "walking",
    "width": 3840,
    "height": 2880,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "white-villages": {
    "base": "white-villages",
    "width": 3840,
    "height": 2880,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "wine": {
    "base": "wine",
    "width": 2048,
    "height": 1363,
    "fallbackWidth": 800,
    "fallbackHeight": 532,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
